name = "backend"
compatibility_date = "2024-09-09"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
<<<<<<< HEAD
DATABASE_URL="URL accelerate"
JWT_SECRET = "mysceret"
=======
DATABASE_URL=""
JWT_SECRET = ""
>>>>>>> f56a8fd (added the vercel json)



# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""


# [ai]
# binding = "AI"
